name: Build dist files
on:
  push:
    branches:
      - master

jobs:
  run:
    name: Build files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: woodcock3
          author_email: woodcock3-fake-email
          message: "Add dist files"
          add: "dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
